# Generated by Django 3.2.13 on 2024-01-30 17:23

from django.db import migrations, models
import django.db.models.deletion
import matrevy.revues.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Revue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-slug')),
                ('title', models.CharField(max_length=200, verbose_name='titel')),
                ('description', models.TextField(blank=True, verbose_name='beskrivelse')),
                ('opening_date', models.DateField(verbose_name='premierdato')),
                ('poster', models.ImageField(blank=True, upload_to=matrevy.revues.models.upload_poster_path, verbose_name='plakat')),
            ],
            options={
                'verbose_name': 'revy',
                'verbose_name_plural': 'revyer',
                'ordering': ['-opening_date'],
            },
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titel')),
                ('type', models.CharField(choices=[('SKETCH', 'Sketch'), ('SONG', 'Song'), ('VIDEO', 'Video')], default='SKETCH', max_length=20, verbose_name='type')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='varighed')),
                ('act_no', models.PositiveIntegerField()),
                ('scene_no', models.PositiveIntegerField()),
                ('revue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revues.revue')),
            ],
            options={
                'verbose_name': 'scene',
                'verbose_name_plural': 'scener',
                'ordering': ['-revue', 'act_no', 'scene_no'],
            },
        ),
    ]
